services:
  _defaults:
    autowire: true
    autoconfigure: true

  WebEtDesign\SortableBundle\:
    resource: '../../*'
    exclude:
      - '../../DependencyInjection'
      - '../../Entity'

  WebEtDesign\SortableBundle\Controller\:
    resource: '../../Controller'
    tags: [ 'controller.service_arguments' ]